stages:
  - checks
  - version_check
  - specs
  - diffs
  - sitedoc
  - integration
  - live_runs
  - merge_request
  - promote
  - rollout
  - postcheck
pages:
  stage: sitedoc
  script:
    - rm -rf doc public .yardoc
    - puppet strings generate site/\*\*/manifests/\*.pp site/\*\*/manifests/\*\*/\*.pp site/\*\*/manifests/\*\*/\*\*/\*.pp site/\*\*/functions/\*\*/\*.pp manifests/\*.pp
    - mv doc public
  tags:
    - deploy_puppet
  artifacts:
    paths:
    - public
    expire_in: '30 day'
    # Puppet lint tests.
puppet-lint:
  stage: checks
  script: "/usr/local/bin/puppet-lint"
  cache:
    untracked: true
    paths:
    - modules/
  tags:
    - test_puppet
  except:
    - testing
    - production
  only:
    - branches
  allow_failure: true   # The job can fail without blocking the pipeline

