stages:
  - sitedoc
  - lint
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TERM: vt100
lint:
  stage: lint
  script:
    - true puppet-lint manifests/*.pp
sitedoc:
  stage: sitedoc
  script:
    - rm -rf doc public .yardoc
    - apk add ruby
    - gem install puppet
    - gem install json
    - puppet strings generate site/\*\*/manifests/\*.pp site/\*\*/manifests/\*\*/\*.pp site/\*\*/manifests/\*\*/\*\*/\*.pp site/\*\*/functions/\*\*/\*.pp manifests/\*.pp
    - mv doc public
  artifacts:
    paths:
    - public
    expire_in: '30 day'
  only:
    - master
